[build]
  command = "npm run build"
  publish = "client/build"
  functions = "server"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/socket/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 